services:
  pikaraoke:
    ports:
      - 5555:5555
    volumes:
      - ~/pikaraoke-songs:/app/pikaraoke-songs
      - ~/.pikaraoke:/home/pikaraoke/.pikaraoke
    image: ghcr.io/adl101010/pikaraoke:stable
    command: -u http://<YOUR_LAN_IP>:5555
networks: {}
